# Generated by Django 5.0.6 on 2024-07-02 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tweet',
        ),
    ]
